junctions = [["1", "4", "5", "8"], ["7", "8", "9", "6"], ["5", "6", "3", "2"], ["5", "8", "9", "6"]]
timestamps = [["1", "2", "3", "4"], ["2", "3", "4", "5"], ["1", "3", "4", "5"], ["2", "3", "5", "6"]]
